apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-release-git-helm-towards5gs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: repo/free5gc-1.1.3.tgz
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: hello-gitrepo
  interval: 10s
  targetNamespace: test-5gs