apiVersion: v1
kind: ConfigMap
metadata:
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  gitrepoName: test-gitrepo
  chartName: hello-world
  namespace: hello
  replicas: "4"
